USE Hospital
GO

DECLARE @TableName NVARCHAR(100)

DECLARE CUR CURSOR FOR
	SELECT TABLE_NAME
	FROM   INFORMATION_SCHEMA.TABLES
	WHERE  TABLE_TYPE = 'BASE TABLE'
--OPEN CURSOR
OPEN CUR
--Fetch First Row
FETCH NEXT FROM CUR INTO @TableName
--Loop
DECLARE @CTriggerName NVARCHAR(100)
DECLARE @UTriggerName NVARCHAR(100)

WHILE @@FETCH_STATUS = 0
BEGIN
	SET @CTriggerName = 'trg_' + @TableName + '_DCR_UCR'
	SET @UTriggerName = 'trg_' + @TableName + '_DLC_ULC'

	EXECUTE('DROP TRIGGER ' + @CTriggerName);
	EXECUTE('DROP TRIGGER ' + @UTriggerName);

	FETCH NEXT FROM CUR INTO @TableName

END

CLOSE CUR
DEALLOCATE CUR